using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class FerryShuttleWindow : FancyWindow,
    IComputerWindow<FerryConsoleBoundUserInterfaceState>
{
    public event Action? OnLaunchPressed;

    public FerryShuttleWindow()
    {
        RobustXamlLoader.Load(this);
        LaunchButton.OnPressed += OnLaunchButtonPressed;


    }

    private void OnLaunchButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        OnLaunchPressed?.Invoke();
    }

    public void UpdateState(FerryConsoleBoundUserInterfaceState state)
    {
        LaunchButton.Disabled = !state.AllowSend;
    }

}

