using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.Ghost.Controls.Roles
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostRoleInfoBox : BoxContainer
    {
        public GhostRoleInfoBox(string name, string description, string rules)
        {
            RobustXamlLoader.Load(this);

            Title.Text = name;
            Log.Debug("type: " + rules);
            RoleType.SetMessage(FormattedMessage.FromMarkupPermissive(rules));
            Description.SetMessage(description);
        }
    }
}
